# Introduction {#intro}

`r if(knitr::is_latex_output()) '\\pagenumbering{arabic}
\\setcounter{page}{1}'`

Relating motor output to its sensory consequences is critical to simple movements and more complex behaviour. In the case of innate sensorimotor contingencies, the brain is thought to make use of corollary discharges, which cancel out the sensory consequence of a motor action by subtracting its predicted effect from the sensory input and play an important role even in simple circuits [@poulet2003cricket]. Whether they are mediated by elementary computations or require more finely tuned control, these corollary discharges demonstrate the existence and usefulness of a generative model of sensorimotor contingencies [@miall1996forward]. These innate contingencies are also represented in sensory areas of the cortex where neurons signal the mismatch between visual input and predicted visual flow [@keller2012sensorimotor; @leinweber2017sensorimotor], and between vocalizations and auditory feedback [@eliades2018auditory].

While the representation of innate sensorimotor contingencies is important for everyday behaviour, it is equally important to be able to recognize novel contingencies in dynamically changing environments. Humans and animals are adept at extracting statistical information from volatile environments [@behrens2007information]. This is mediated, in part, by sensory areas of the cortex, which are thought to construct a model of their environment [@berkes2011spontaneous]. In particular, some neurons respond more strongly to unexpected stimuli. For example, neurons in auditory cortex encode oddballs, tones that are unlikely according to the recent history of stimulus presentation [@gill2008surprise; @rubin2016representation]. This model guides how multisensory as well as sensorimotor information is integrated [@gallistel2001rat; @ernst2002humans; @kording2004force; @kording2004bayesian].

In contrast to statistical patterns in the environment, artificial sensorimotor contingencies take the observer into account as a causal actor. Such contingencies are abundant in our daily lives, in particular in light of technological advancement, but it is advantageous for many animals to learn such novel rules, as well. Relatively little research has been carried out on this. However, @aronov2017grid found that training rats to manipulate the frequency of a presented sound by pressing a lever resulted in the induced virtual tonespace being represented in a grid cell-like fashion in the hippocampal-entorhinal circuit. Furthermore, it has been shown that neurons in auditory cortex suppress artificial sensory consequences of movement when mice are passively presented with such a contingency [@schneider2018cortical].

In order to investigate the emergence of novel, behaviourally relevant sensorimotor contingencies, we trained mice to manipulate stimulus frequency by their licking behaviour while recording from large numbers of neurons in auditory cortex using 2-photon imaging. Mice were presented with tones at a regular interval and position in front of two spouts. Licking one of them led to a decrease in frequency of the presented tones, licking the other one led to an increase in frequency. In accordance with this contingency, the mice had to navigate to a rewarded frequency region in order to receive a drop of water. In this dissertation, I am going to investigate whether the mice were able to learn this task and what effect the presented contingency had on the activity of neurons in auditory cortex.
